# Generated by Django 3.2 on 2023-10-08 13:54

import uuid

import django.contrib.postgres.fields
import notification.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql='CREATE SCHEMA IF NOT EXISTS notification;',
            reverse_sql='DROP SCHEMA IF EXISTS notification CASCADE;'
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email')], max_length=10, verbose_name='Способ уведомления')),
                ('name', models.CharField(max_length=255, verbose_name='Название уведомления')),
                ('title', models.CharField(max_length=255, validators=[notification.validators.validate_jinja_template], verbose_name='Заголовок')),
                ('content', models.TextField(validators=[notification.validators.validate_jinja_template], verbose_name='Содержимое')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('placeholders', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None, verbose_name='Список переменных')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
            ],
            options={
                'verbose_name': 'Шаблон',
                'verbose_name_plural': 'Шаблоны',
                'db_table': 'notification"."template',
            },
        ),
    ]
