"""Add service and m2m connection with user, extend user model

Revision ID: 3a64ddbe4182
Revises: 6dba2e92fe2b
Create Date: 2023-06-14 22:45:58.068632

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3a64ddbe4182'
down_revision = '6dba2e92fe2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='users'
    )
    op.create_table('user_service',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('user_service_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['users.service.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user.id'], ),
    sa.PrimaryKeyConstraint('service_id', 'user_service_id'),
    schema='users'
    )
    op.add_column('user', sa.Column('email', sa.String(length=50), nullable=True), schema='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email', schema='users')
    op.drop_table('user_service', schema='users')
    op.drop_table('service', schema='users')
    # ### end Alembic commands ###
