"""empty message

Revision ID: e5364c11616c
Revises: 3a64ddbe4182
Create Date: 2023-10-08 14:00:08.686356

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e5364c11616c'
down_revision = '3a64ddbe4182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('time_zone', sa.String(length=100), nullable=False, server_default='Europe/Moscow'), schema='users')
    op.add_column('user', sa.Column('notifications_enabled', sa.Boolean(), nullable=False, server_default='False'), schema='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'notifications_enabled', schema='users')
    op.drop_column('user', 'time_zone', schema='users')
    # ### end Alembic commands ###
